healthQ_gpt-4o_cot_fn:
  prompt_template: "prompt_template.txt"
  system_prompt: "system_prompt.txt"
  fn_completions: "openai_chat_completions"
  completions_kwargs:
    model_name: "gpt-4o"
    api_account: "healthQ"
    max_new_tokens: 500
    temperature: 1.0
    request_timeout: 15
    max_retry: 20
    price_per_token: 0
    requires_chatml: True
  fn_completion_parser: "ranking_parser"
  batch_size: 1
  self_consistency: 3
