actor_learning_rate: 5e-7
prompt_data: stellalisy/healthQ_preference@unfiltered
prompt_split: train
eval_split: validation
input_key: context
apply_chat_template: true
pretrain: stellalisy/llama-3.2-3b-instruct_sft_healthQ_lr5e-6_ep2
reward_pretrain: reward_models/llama-3.2-3b-rm_lr9e-6_filtered
save_path: ppo_models/llama-3.2-3b-instruct_lr5e-6_ep2/rm_lr9e-6_ppo_lr5e-7
ckpt_path: ppo_models/llama-3.2-3b-instruct_lr5e-6_ep2/rm_lr9e-6_ppo_lr5e-7
max_ckpt_num: 1
logging_steps: 1
save_steps: 10
eval_steps: 10
load_checkpoint: true
train_batch_size: 256
micro_train_batch_size: 1
bf16: true
max_epochs: 1
prompt_max_len: 2048
generate_max_len: 64
zero_stage: 1
flash_attn: true
gradient_checkpointing: true
l2: 0
lr_warmup_ratio: 0.03
use_wandb: 'yes'
wandb_host: https://api.wandb.ai
wandb_project: healthQ_ppo
wandb_group: hyperparameter
wandb_run_name: llama-3.2-3b_rm_lr9e-6_ppo_lr5e-7
