learning_rate: 5e-7
beta: 2
dataset: stellalisy/MediQ_AskDocs_preference@filtered
dataset_probs: 1.0
train_split: train
eval_split: validation
prompt_key: context
chosen_key: chosen
rejected_key: rejected
apply_chat_template: true
pretrain: stellalisy/llama-3.2-3b-instruct_sft_healthQ_lr5e-6_ep2
save_path: models/llama-3.2-3b-instruct_lr5e-6_ep2/dpo_lr5e-7_beta2_filtered
ckpt_path: models/llama-3.2-3b-instruct_lr5e-6_ep2/dpo_lr5e-7_beta2_filtered
max_ckpt_num: 1
logging_steps: 1
save_steps: 10
eval_steps: 10
load_checkpoint: true
train_batch_size: 256
micro_train_batch_size: 1
bf16: true
max_epochs: 1
max_len: 2048
zero_stage: 3
flash_attn: true
gradient_checkpointing: true
l2: 0
lr_warmup_ratio: 0.03
use_wandb: 'yes'
wandb_project: healthq_dpo_filtered
wandb_group: dpo_compare
wandb_run_name: llama-3.2-3b-instruct_lr5e-6_ep2_dpo_lr5e-7_beta2_filtered
packing_samples: true
max_new_tokens: 64
