apply_chat_template: true
bf16: true
dataset: stellalisy/MediQ_askdocs_sft
dataset_probs: 1.0
flash_attn: true
gradient_checkpointing: true
input_key: messages
l2: 0
learning_rate: 5e-6
load_checkpoint: true
lr_scheduler: cosine_with_min_lr
lr_warmup_ratio: 0.03
max_epochs: 2
max_len: 2048
micro_train_batch_size: 2
pretrain: meta-llama/Llama-3.2-3B-Instruct
save_path: models/llama-3.2-3b-instruct_lr5e-6_ep2
ckpt_path: models/llama-3.2-3b-instruct_lr5e-6_ep2
max_ckpt_num: 1
logging_steps: 1
save_steps: 10
eval_steps: 10
train_batch_size: 256
train_split: train
eval_split: validation
use_wandb: 'yes'
wandb_project: healthQ_sft
wandb_group: hyperparameter
wandb_run_name: llama-3.2-3b-instruct_lr5e-6_ep2
zero_stage: 1
packing_samples: true
max_new_tokens: 64
