learning_rate: 9e-6
dataset: stellalisy/MediQ_AskDocs_preference@filtered
dataset_probs: 1.0
train_split: train
eval_split: validation
prompt_key: context
chosen_key: chosen
rejected_key: rejected
apply_chat_template: true
pretrain: meta-llama/Llama-3.2-3B-Instruct
save_path: reward_models/llama-3.2-3b-rm_lr9e-6_filtered
ckpt_path: reward_models/llama-3.2-3b-rm_lr9e-6_filtered
max_ckpt_num: 1
logging_steps: 1
save_steps: 10
eval_steps: 10
load_checkpoint: true
train_batch_size: 256
micro_train_batch_size: 2
bf16: true
max_epochs: 1
max_len: 2048
zero_stage: 1
flash_attn: true
gradient_checkpointing: true
l2: 0
lr_warmup_ratio: 0.03
use_wandb: 'yes'
wandb_host: https://api.wandb.ai
wandb_project: healthQ_rm
wandb_group: hyperparameter
wandb_run_name: llama-3.2-3b_rm_lr9e-6_filtered
packing_samples: true
